version: '2'

services:

#  prometheus:
#    image: prom/prometheus:latest
#    command:
#        - '-config.file=/etc/prometheus/prometheus.yml'
#    links:
#      - cadvisor:cadvisor
#    ports:
#        - '9090:9090'
#    volumes:
#      - ./prometheus_data:/prometheus
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter-102:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'

  cadvisor-102:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
